# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/quantumPhys',
                'doc_host': 'https://javierargu.github.io',
                'git_url': 'https://github.com/javierargu/quantumPhys',
                'lib_path': 'quantumPhys'},
  'syms': {'quantumPhys.core': {'quantumPhys.core.foo': ('intro.html#foo', 'quantumPhys/core.py')}}}
